/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as TempIndexRouteImport } from './routes/temp/index'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as TempRoomRouteImport } from './routes/temp/room'
import { Route as TempReservationsRouteImport } from './routes/temp/reservations'
import { Route as TempBuildingRouteImport } from './routes/temp/building'
import { Route as authenticatedTableExportRouteImport } from './routes/(authenticated)/table-export'
import { Route as authenticatedStylesRouteImport } from './routes/(authenticated)/styles'
import { Route as authenticatedNotificationRouteImport } from './routes/(authenticated)/notification'
import { Route as authenticatedMeRouteImport } from './routes/(authenticated)/me'
import { Route as authenticatedFormRouteImport } from './routes/(authenticated)/form'
import { Route as authenticatedFetchRouteImport } from './routes/(authenticated)/fetch'
import { Route as TempResourcesIndexRouteImport } from './routes/temp/resources/index'
import { Route as TempResourcesResourceIdRouteImport } from './routes/temp/resources/$resourceId'
import { Route as TempAdminResourcesRouteImport } from './routes/temp/admin/resources'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const TempIndexRoute = TempIndexRouteImport.update({
  id: '/temp/',
  path: '/temp/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const TempRoomRoute = TempRoomRouteImport.update({
  id: '/temp/room',
  path: '/temp/room',
  getParentRoute: () => rootRouteImport,
} as any)
const TempReservationsRoute = TempReservationsRouteImport.update({
  id: '/temp/reservations',
  path: '/temp/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const TempBuildingRoute = TempBuildingRouteImport.update({
  id: '/temp/building',
  path: '/temp/building',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedTableExportRoute =
  authenticatedTableExportRouteImport.update({
    id: '/table-export',
    path: '/table-export',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedStylesRoute = authenticatedStylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedNotificationRoute =
  authenticatedNotificationRouteImport.update({
    id: '/notification',
    path: '/notification',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMeRoute = authenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedFormRoute = authenticatedFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedFetchRoute = authenticatedFetchRouteImport.update({
  id: '/fetch',
  path: '/fetch',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const TempResourcesIndexRoute = TempResourcesIndexRouteImport.update({
  id: '/temp/resources/',
  path: '/temp/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const TempResourcesResourceIdRoute = TempResourcesResourceIdRouteImport.update({
  id: '/temp/resources/$resourceId',
  path: '/temp/resources/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TempAdminResourcesRoute = TempAdminResourcesRouteImport.update({
  id: '/temp/admin/resources',
  path: '/temp/admin/resources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/fetch': typeof authenticatedFetchRoute
  '/form': typeof authenticatedFormRoute
  '/me': typeof authenticatedMeRoute
  '/notification': typeof authenticatedNotificationRoute
  '/styles': typeof authenticatedStylesRoute
  '/table-export': typeof authenticatedTableExportRoute
  '/temp/building': typeof TempBuildingRoute
  '/temp/reservations': typeof TempReservationsRoute
  '/temp/room': typeof TempRoomRoute
  '/': typeof authenticatedIndexRoute
  '/temp': typeof TempIndexRoute
  '/temp/admin/resources': typeof TempAdminResourcesRoute
  '/temp/resources/$resourceId': typeof TempResourcesResourceIdRoute
  '/temp/resources': typeof TempResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/fetch': typeof authenticatedFetchRoute
  '/form': typeof authenticatedFormRoute
  '/me': typeof authenticatedMeRoute
  '/notification': typeof authenticatedNotificationRoute
  '/styles': typeof authenticatedStylesRoute
  '/table-export': typeof authenticatedTableExportRoute
  '/temp/building': typeof TempBuildingRoute
  '/temp/reservations': typeof TempReservationsRoute
  '/temp/room': typeof TempRoomRoute
  '/': typeof authenticatedIndexRoute
  '/temp': typeof TempIndexRoute
  '/temp/admin/resources': typeof TempAdminResourcesRoute
  '/temp/resources/$resourceId': typeof TempResourcesResourceIdRoute
  '/temp/resources': typeof TempResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/(authenticated)/fetch': typeof authenticatedFetchRoute
  '/(authenticated)/form': typeof authenticatedFormRoute
  '/(authenticated)/me': typeof authenticatedMeRoute
  '/(authenticated)/notification': typeof authenticatedNotificationRoute
  '/(authenticated)/styles': typeof authenticatedStylesRoute
  '/(authenticated)/table-export': typeof authenticatedTableExportRoute
  '/temp/building': typeof TempBuildingRoute
  '/temp/reservations': typeof TempReservationsRoute
  '/temp/room': typeof TempRoomRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/temp/': typeof TempIndexRoute
  '/temp/admin/resources': typeof TempAdminResourcesRoute
  '/temp/resources/$resourceId': typeof TempResourcesResourceIdRoute
  '/temp/resources/': typeof TempResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/fetch'
    | '/form'
    | '/me'
    | '/notification'
    | '/styles'
    | '/table-export'
    | '/temp/building'
    | '/temp/reservations'
    | '/temp/room'
    | '/'
    | '/temp'
    | '/temp/admin/resources'
    | '/temp/resources/$resourceId'
    | '/temp/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/fetch'
    | '/form'
    | '/me'
    | '/notification'
    | '/styles'
    | '/table-export'
    | '/temp/building'
    | '/temp/reservations'
    | '/temp/room'
    | '/'
    | '/temp'
    | '/temp/admin/resources'
    | '/temp/resources/$resourceId'
    | '/temp/resources'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/about'
    | '/(authenticated)/fetch'
    | '/(authenticated)/form'
    | '/(authenticated)/me'
    | '/(authenticated)/notification'
    | '/(authenticated)/styles'
    | '/(authenticated)/table-export'
    | '/temp/building'
    | '/temp/reservations'
    | '/temp/room'
    | '/(authenticated)/'
    | '/temp/'
    | '/temp/admin/resources'
    | '/temp/resources/$resourceId'
    | '/temp/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  TempBuildingRoute: typeof TempBuildingRoute
  TempReservationsRoute: typeof TempReservationsRoute
  TempRoomRoute: typeof TempRoomRoute
  TempIndexRoute: typeof TempIndexRoute
  TempAdminResourcesRoute: typeof TempAdminResourcesRoute
  TempResourcesResourceIdRoute: typeof TempResourcesResourceIdRoute
  TempResourcesIndexRoute: typeof TempResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp/': {
      id: '/temp/'
      path: '/temp'
      fullPath: '/temp'
      preLoaderRoute: typeof TempIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/temp/room': {
      id: '/temp/room'
      path: '/temp/room'
      fullPath: '/temp/room'
      preLoaderRoute: typeof TempRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp/reservations': {
      id: '/temp/reservations'
      path: '/temp/reservations'
      fullPath: '/temp/reservations'
      preLoaderRoute: typeof TempReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp/building': {
      id: '/temp/building'
      path: '/temp/building'
      fullPath: '/temp/building'
      preLoaderRoute: typeof TempBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/table-export': {
      id: '/(authenticated)/table-export'
      path: '/table-export'
      fullPath: '/table-export'
      preLoaderRoute: typeof authenticatedTableExportRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/styles': {
      id: '/(authenticated)/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof authenticatedStylesRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/notification': {
      id: '/(authenticated)/notification'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof authenticatedNotificationRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/me': {
      id: '/(authenticated)/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof authenticatedMeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/form': {
      id: '/(authenticated)/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof authenticatedFormRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/fetch': {
      id: '/(authenticated)/fetch'
      path: '/fetch'
      fullPath: '/fetch'
      preLoaderRoute: typeof authenticatedFetchRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/temp/resources/': {
      id: '/temp/resources/'
      path: '/temp/resources'
      fullPath: '/temp/resources'
      preLoaderRoute: typeof TempResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp/resources/$resourceId': {
      id: '/temp/resources/$resourceId'
      path: '/temp/resources/$resourceId'
      fullPath: '/temp/resources/$resourceId'
      preLoaderRoute: typeof TempResourcesResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temp/admin/resources': {
      id: '/temp/admin/resources'
      path: '/temp/admin/resources'
      fullPath: '/temp/admin/resources'
      preLoaderRoute: typeof TempAdminResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedFetchRoute: typeof authenticatedFetchRoute
  authenticatedFormRoute: typeof authenticatedFormRoute
  authenticatedMeRoute: typeof authenticatedMeRoute
  authenticatedNotificationRoute: typeof authenticatedNotificationRoute
  authenticatedStylesRoute: typeof authenticatedStylesRoute
  authenticatedTableExportRoute: typeof authenticatedTableExportRoute
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedFetchRoute: authenticatedFetchRoute,
  authenticatedFormRoute: authenticatedFormRoute,
  authenticatedMeRoute: authenticatedMeRoute,
  authenticatedNotificationRoute: authenticatedNotificationRoute,
  authenticatedStylesRoute: authenticatedStylesRoute,
  authenticatedTableExportRoute: authenticatedTableExportRoute,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  TempBuildingRoute: TempBuildingRoute,
  TempReservationsRoute: TempReservationsRoute,
  TempRoomRoute: TempRoomRoute,
  TempIndexRoute: TempIndexRoute,
  TempAdminResourcesRoute: TempAdminResourcesRoute,
  TempResourcesResourceIdRoute: TempResourcesResourceIdRoute,
  TempResourcesIndexRoute: TempResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
